//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Game/NewInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MobaInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MobaInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NewInputs"",
    ""maps"": [
        {
            ""name"": ""movearound"",
            ""id"": ""dd8592f9-12c6-4844-b84c-64d8c2845411"",
            ""actions"": [
                {
                    ""name"": ""MobaInputActions"",
                    ""type"": ""Button"",
                    ""id"": ""8a7b4108-bdf5-4731-89b9-2a9831464d9e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""783d0538-7997-4e78-9484-7336291dbe56"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MobaInputActions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // movearound
        m_movearound = asset.FindActionMap("movearound", throwIfNotFound: true);
        m_movearound_MobaInputActions = m_movearound.FindAction("MobaInputActions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // movearound
    private readonly InputActionMap m_movearound;
    private List<IMovearoundActions> m_MovearoundActionsCallbackInterfaces = new List<IMovearoundActions>();
    private readonly InputAction m_movearound_MobaInputActions;
    public struct MovearoundActions
    {
        private @MobaInputActions m_Wrapper;
        public MovearoundActions(@MobaInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MobaInputActions => m_Wrapper.m_movearound_MobaInputActions;
        public InputActionMap Get() { return m_Wrapper.m_movearound; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovearoundActions set) { return set.Get(); }
        public void AddCallbacks(IMovearoundActions instance)
        {
            if (instance == null || m_Wrapper.m_MovearoundActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovearoundActionsCallbackInterfaces.Add(instance);
            @MobaInputActions.started += instance.OnMobaInputActions;
            @MobaInputActions.performed += instance.OnMobaInputActions;
            @MobaInputActions.canceled += instance.OnMobaInputActions;
        }

        private void UnregisterCallbacks(IMovearoundActions instance)
        {
            @MobaInputActions.started -= instance.OnMobaInputActions;
            @MobaInputActions.performed -= instance.OnMobaInputActions;
            @MobaInputActions.canceled -= instance.OnMobaInputActions;
        }

        public void RemoveCallbacks(IMovearoundActions instance)
        {
            if (m_Wrapper.m_MovearoundActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovearoundActions instance)
        {
            foreach (var item in m_Wrapper.m_MovearoundActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovearoundActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovearoundActions @movearound => new MovearoundActions(this);
    public interface IMovearoundActions
    {
        void OnMobaInputActions(InputAction.CallbackContext context);
    }
}
